### ISSUE TITLE
Many unused parameters in `acf_fuctions.py`

### ISSUE THREAD

**Issue by hamogu** [alexbinks/tessilator#10]
Many functions in `acf_functions.py` take parameter that are never used, e.g. `def plot_fft(fits_result,process_result, plot_peaks=True, **plt_kwargs)` never uses the `fits_result`, all the plotting is done from the `process_result`. 

Another example is 
```Python
process_LightCurve(lc, bs=cadence, precleaned=False,
                        transit=None,
                        max_lag=None, smooth=None, sector_label=None,
                        prot_prior='fft', prot_prior_func=None, prot_prior_func_kwargs={}):
```
Of all those parameters three (`precleaned`, `transit`, and `sector_label`) are never used. There are several other examples in the same module. Yet, all those parameters are written down in the docs with no hint that they are, in fact, useless.

I suggest we clean that up. For once, it's confusing to users if they need to set a parameter that does not influence what happens.

However, in some cases, I'm not sure if the fact that those parameters are never used it intentional or if it's a bug, e.g. should the `sector_number` be passed down to into `calc_parabolas` and it's a big that it's not?

That's why I'm opening this as an issue and not as a PR, because I'm not sure which ones I can remove without harm.

Of course, sometimes one leaves in an old parameters for backwards compatiblity. Eg. if users in version 0.4 needed to set `precleaned` it makes sense to also accept that parameters in version 0.5, so that they old code using tessilator does not break. In that case, that parameter should be marked and/or documented as deprecated though, so users at least know what's going on. And, of course, we want to eventually remove it. As we prepare for the first release that comes with a paper though, I fell now is a good time to actually remove stuff we don't need.

**Comment by hamogu** [comment]
I should say that this is found from "static code analysis", i.e. my editor looking if variable names defined at one point in the code actually come up again somewhere below in the code.

**Comment by hamogu** [comment]
I can't find any use of `acf_functions.py` within tessilator at all. I tried to change the function signatures (#12) to get rid of the unused parameters, so I grep-ed through the rest of the tessilator code to change of those functions are called. However, I can't find a single place where functions from this module are imported (except in the test for this module).

Am I missing something?
If we don't use it, why do we have it in there? Is it for a future plan (in that case I'll fix it)? Or left over from a previous experiment (in that case, let's remove it).

**Comment by alexbinks** [comment]
Hi Moritz,
It occurred to me that a few months ago I started to experiment with the ACF methods by simply using the spinspotter code. It's not implemented in tessilator right now, but in case a referee asks us to try this, or if we maybe want to give the ACF method a go in, say, version 1.2, then I'll just keep this in our local directory and stick it in the .gitignore file.

I'll go ahead and close the issue - I think it covers everything.
