### ISSUE TITLE
Hardcoding `sec_max`?

### ISSUE THREAD

**Issue by hamogu** [alexbinks/tessilator#15]
Currently, `sec_max` is hardcoded in `fixedconstants.py`. That means that we need to do a new release of tessilator every time a new sector becomes available, about once per month. I don't think we develop tessilator that fast that we really need that and it seems a lot of effort to promise users to make that release, just to update that one number.
There must be a better way. Can we get that number from e.g. tesscut? Or simply timeout if people ask for a sector that's not existing already? MAybe it's in the error message from TEsscot if I try to retrieve a sector that does not yet exisit and we cna just resurface that error message?

We could set `sec_max` to e.g. 100. Then, we don't have to upgrade every month, but we could still issue a helpful message for typos likes missing commas as in: `sector = [2,5,6,23, 24, 2526]`.

**Comment by alexbinks** [comment]
Maybe we can sort of web-scrape it from the TESS/MIT page.
If you look here --> https://tess.mit.edu/observations/
You'll see there's a section "Current Status", followed by "TESS is in Orbit 157, Sector 75"
...surely there's a way we can grep, or do some kind of regex on the html output to grab whatever number follows "Sector"...

**Comment by alexbinks** [comment]
As much as this looks like an awful solution, and no doubt there is a fancy regex way of doing it, it works like this as long as the TESS/MIT web developers don't change the text layout (I doubt they will, it's been like this for years).

import requests
from bs4 import BeautifulSoup

tess_web = requests.get('https://tess.mit.edu/observations/')
tess_para = soup(text=re.compile("TESS is in Orbit"))
sec_max = int(tess_para[0].split(',')[1].split(' ')[2].split('.')[0])

**Comment by alexbinks** [comment]
it's actually working - for the sake of reducing the number of tasks I'll close the request and git push the new version!
