### ISSUE TITLE
duration is wrong when run from Python

### ISSUE THREAD

**Issue by hamogu** [alexbinks/tessilator#21]
I get "Finished 1 targets in 18 hours, 52 minutes, 59 seconds" when really it's less than a minute. The reason is that the start time is set when the package is first imported:
```Python

print(STARTUP_STRING)
start = datetime.now()

print("\n")
print("Start time: ", start.strftime("%d/%m/%Y %H:%M:%S"))

```
Now, I just leave my computer running overnight and then call `all_source_cutout`. I would expect the timer to start when I call that function. Instead, it uses the timer that was started when the package was imported. 

Easy to fix (just define "start" in the procedure that prints the result, but I'm doing something else right now, so I'm just putting that here as an issue so we don't forget.

**Comment by alexbinks** [comment]
all sorted. Thanks!
